spring:
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:sharding.yml
    hikari:
      maximum-pool-size: 2
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      jakarta:
        persistence:
          jdbc:
            url: jdbc:shardingsphere:classpath:sharding.yml


#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/sharding2
#    username: postgres
#    password: 211999
#    driverClassName: org.postgresql.Driver
#    jpa:
#      properties:
#        hibernate:
#          dialect: org.hibernate.dialect.PostgreSQLDialect
#      hibernate:
#        ddl-auto: update
#      show-sql: true